// Comprehensive ICD-10 Mental Health Diagnosis Codes
export interface ICD10Code {
  code: string;
  description: string;
  category: string;
}

export const icd10MentalHealthCodes: ICD10Code[] = [
  // Anxiety Disorders (F40-F48)
  { code: 'F40.00', description: 'Agoraphobia, unspecified', category: 'Anxiety Disorders' },
  { code: 'F40.01', description: 'Agoraphobia with panic disorder', category: 'Anxiety Disorders' },
  { code: 'F40.02', description: 'Agoraphobia without panic disorder', category: 'Anxiety Disorders' },
  { code: 'F40.10', description: 'Social phobia, unspecified', category: 'Anxiety Disorders' },
  { code: 'F40.11', description: 'Social phobia, generalized', category: 'Anxiety Disorders' },
  { code: 'F40.210', description: 'Arachnophobia', category: 'Anxiety Disorders' },
  { code: 'F40.218', description: 'Other animal type phobia', category: 'Anxiety Disorders' },
  { code: 'F40.228', description: 'Fear of thunderstorms', category: 'Anxiety Disorders' },
  { code: 'F40.230', description: 'Fear of blood', category: 'Anxiety Disorders' },
  { code: 'F40.231', description: 'Fear of injections and transfusions', category: 'Anxiety Disorders' },
  { code: 'F40.232', description: 'Fear of other medical care', category: 'Anxiety Disorders' },
  { code: 'F40.233', description: 'Fear of injury', category: 'Anxiety Disorders' },
  { code: 'F40.240', description: 'Claustrophobia', category: 'Anxiety Disorders' },
  { code: 'F40.241', description: 'Acrophobia', category: 'Anxiety Disorders' },
  { code: 'F40.242', description: 'Fear of bridges', category: 'Anxiety Disorders' },
  { code: 'F40.243', description: 'Fear of flying', category: 'Anxiety Disorders' },
  { code: 'F40.248', description: 'Other situational type phobia', category: 'Anxiety Disorders' },
  { code: 'F40.290', description: 'Androphobia', category: 'Anxiety Disorders' },
  { code: 'F40.291', description: 'Gynophobia', category: 'Anxiety Disorders' },
  { code: 'F40.298', description: 'Other specified phobia', category: 'Anxiety Disorders' },
  { code: 'F41.0', description: 'Panic disorder [episodic paroxysmal anxiety] without agoraphobia', category: 'Anxiety Disorders' },
  { code: 'F41.1', description: 'Generalized anxiety disorder', category: 'Anxiety Disorders' },
  { code: 'F41.3', description: 'Other mixed anxiety disorders', category: 'Anxiety Disorders' },
  { code: 'F41.8', description: 'Other specified anxiety disorders', category: 'Anxiety Disorders' },
  { code: 'F41.9', description: 'Anxiety disorder, unspecified', category: 'Anxiety Disorders' },
  { code: 'F42.2', description: 'Mixed obsessional thoughts and acts', category: 'Anxiety Disorders' },
  { code: 'F42.3', description: 'Hoarding disorder', category: 'Anxiety Disorders' },
  { code: 'F42.4', description: 'Excoriation (skin-picking) disorder', category: 'Anxiety Disorders' },
  { code: 'F42.8', description: 'Other obsessive-compulsive disorder', category: 'Anxiety Disorders' },
  { code: 'F42.9', description: 'Obsessive-compulsive disorder, unspecified', category: 'Anxiety Disorders' },
  { code: 'F43.0', description: 'Acute stress reaction', category: 'Anxiety Disorders' },
  { code: 'F43.10', description: 'Post-traumatic stress disorder, unspecified', category: 'Anxiety Disorders' },
  { code: 'F43.11', description: 'Post-traumatic stress disorder, acute', category: 'Anxiety Disorders' },
  { code: 'F43.12', description: 'Post-traumatic stress disorder, chronic', category: 'Anxiety Disorders' },
  { code: 'F43.20', description: 'Adjustment disorder, unspecified', category: 'Anxiety Disorders' },
  { code: 'F43.21', description: 'Adjustment disorder with depressed mood', category: 'Anxiety Disorders' },
  { code: 'F43.22', description: 'Adjustment disorder with anxiety', category: 'Anxiety Disorders' },
  { code: 'F43.23', description: 'Adjustment disorder with mixed anxiety and depressed mood', category: 'Anxiety Disorders' },
  { code: 'F43.24', description: 'Adjustment disorder with disturbance of conduct', category: 'Anxiety Disorders' },
  { code: 'F43.25', description: 'Adjustment disorder with mixed disturbance of emotions and conduct', category: 'Anxiety Disorders' },
  { code: 'F43.29', description: 'Adjustment disorder with other symptoms', category: 'Anxiety Disorders' },
  
  // Depressive Disorders (F32-F34)
  { code: 'F32.0', description: 'Major depressive disorder, single episode, mild', category: 'Depressive Disorders' },
  { code: 'F32.1', description: 'Major depressive disorder, single episode, moderate', category: 'Depressive Disorders' },
  { code: 'F32.2', description: 'Major depressive disorder, single episode, severe without psychotic features', category: 'Depressive Disorders' },
  { code: 'F32.3', description: 'Major depressive disorder, single episode, severe with psychotic features', category: 'Depressive Disorders' },
  { code: 'F32.4', description: 'Major depressive disorder, single episode, in partial remission', category: 'Depressive Disorders' },
  { code: 'F32.5', description: 'Major depressive disorder, single episode, in full remission', category: 'Depressive Disorders' },
  { code: 'F32.81', description: 'Premenstrual dysphoric disorder', category: 'Depressive Disorders' },
  { code: 'F32.89', description: 'Other specified depressive episodes', category: 'Depressive Disorders' },
  { code: 'F32.9', description: 'Major depressive disorder, single episode, unspecified', category: 'Depressive Disorders' },
  { code: 'F33.0', description: 'Major depressive disorder, recurrent, mild', category: 'Depressive Disorders' },
  { code: 'F33.1', description: 'Major depressive disorder, recurrent, moderate', category: 'Depressive Disorders' },
  { code: 'F33.2', description: 'Major depressive disorder, recurrent severe without psychotic features', category: 'Depressive Disorders' },
  { code: 'F33.3', description: 'Major depressive disorder, recurrent, severe with psychotic symptoms', category: 'Depressive Disorders' },
  { code: 'F33.40', description: 'Major depressive disorder, recurrent, in remission, unspecified', category: 'Depressive Disorders' },
  { code: 'F33.41', description: 'Major depressive disorder, recurrent, in partial remission', category: 'Depressive Disorders' },
  { code: 'F33.42', description: 'Major depressive disorder, recurrent, in full remission', category: 'Depressive Disorders' },
  { code: 'F33.8', description: 'Other recurrent depressive disorders', category: 'Depressive Disorders' },
  { code: 'F33.9', description: 'Major depressive disorder, recurrent, unspecified', category: 'Depressive Disorders' },
  { code: 'F34.0', description: 'Cyclothymic disorder', category: 'Depressive Disorders' },
  { code: 'F34.1', description: 'Dysthymic disorder', category: 'Depressive Disorders' },
  { code: 'F34.81', description: 'Disruptive mood dysregulation disorder', category: 'Depressive Disorders' },
  { code: 'F34.89', description: 'Other specified persistent mood disorders', category: 'Depressive Disorders' },
  { code: 'F34.9', description: 'Persistent mood [affective] disorder, unspecified', category: 'Depressive Disorders' },

  // Bipolar Disorders (F31)
  { code: 'F31.0', description: 'Bipolar disorder, current episode hypomanic', category: 'Bipolar Disorders' },
  { code: 'F31.10', description: 'Bipolar disorder, current episode manic without psychotic features, unspecified', category: 'Bipolar Disorders' },
  { code: 'F31.11', description: 'Bipolar disorder, current episode manic without psychotic features, mild', category: 'Bipolar Disorders' },
  { code: 'F31.12', description: 'Bipolar disorder, current episode manic without psychotic features, moderate', category: 'Bipolar Disorders' },
  { code: 'F31.13', description: 'Bipolar disorder, current episode manic without psychotic features, severe', category: 'Bipolar Disorders' },
  { code: 'F31.2', description: 'Bipolar disorder, current episode manic severe with psychotic features', category: 'Bipolar Disorders' },
  { code: 'F31.30', description: 'Bipolar disorder, current episode depressed, mild or moderate severity, unspecified', category: 'Bipolar Disorders' },
  { code: 'F31.31', description: 'Bipolar disorder, current episode depressed, mild', category: 'Bipolar Disorders' },
  { code: 'F31.32', description: 'Bipolar disorder, current episode depressed, moderate', category: 'Bipolar Disorders' },
  { code: 'F31.4', description: 'Bipolar disorder, current episode depressed, severe, without psychotic features', category: 'Bipolar Disorders' },
  { code: 'F31.5', description: 'Bipolar disorder, current episode depressed, severe, with psychotic features', category: 'Bipolar Disorders' },
  { code: 'F31.60', description: 'Bipolar disorder, current episode mixed, unspecified', category: 'Bipolar Disorders' },
  { code: 'F31.61', description: 'Bipolar disorder, current episode mixed, mild', category: 'Bipolar Disorders' },
  { code: 'F31.62', description: 'Bipolar disorder, current episode mixed, moderate', category: 'Bipolar Disorders' },
  { code: 'F31.63', description: 'Bipolar disorder, current episode mixed, severe, without psychotic features', category: 'Bipolar Disorders' },
  { code: 'F31.64', description: 'Bipolar disorder, current episode mixed, severe, with psychotic features', category: 'Bipolar Disorders' },
  { code: 'F31.70', description: 'Bipolar disorder, currently in remission, most recent episode unspecified', category: 'Bipolar Disorders' },
  { code: 'F31.71', description: 'Bipolar disorder, in partial remission, most recent episode hypomanic', category: 'Bipolar Disorders' },
  { code: 'F31.72', description: 'Bipolar disorder, in full remission, most recent episode hypomanic', category: 'Bipolar Disorders' },
  { code: 'F31.73', description: 'Bipolar disorder, in partial remission, most recent episode manic', category: 'Bipolar Disorders' },
  { code: 'F31.74', description: 'Bipolar disorder, in full remission, most recent episode manic', category: 'Bipolar Disorders' },
  { code: 'F31.75', description: 'Bipolar disorder, in partial remission, most recent episode depressed', category: 'Bipolar Disorders' },
  { code: 'F31.76', description: 'Bipolar disorder, in full remission, most recent episode depressed', category: 'Bipolar Disorders' },
  { code: 'F31.77', description: 'Bipolar disorder, in partial remission, most recent episode mixed', category: 'Bipolar Disorders' },
  { code: 'F31.78', description: 'Bipolar disorder, in full remission, most recent episode mixed', category: 'Bipolar Disorders' },
  { code: 'F31.81', description: 'Bipolar II disorder', category: 'Bipolar Disorders' },
  { code: 'F31.89', description: 'Other bipolar disorder', category: 'Bipolar Disorders' },
  { code: 'F31.9', description: 'Bipolar disorder, unspecified', category: 'Bipolar Disorders' },

  // Schizophrenia Spectrum (F20-F29)
  { code: 'F20.0', description: 'Paranoid schizophrenia', category: 'Schizophrenia Spectrum' },
  { code: 'F20.1', description: 'Disorganized schizophrenia', category: 'Schizophrenia Spectrum' },
  { code: 'F20.2', description: 'Catatonic schizophrenia', category: 'Schizophrenia Spectrum' },
  { code: 'F20.3', description: 'Undifferentiated schizophrenia', category: 'Schizophrenia Spectrum' },
  { code: 'F20.5', description: 'Residual schizophrenia', category: 'Schizophrenia Spectrum' },
  { code: 'F20.81', description: 'Schizophreniform disorder', category: 'Schizophrenia Spectrum' },
  { code: 'F20.89', description: 'Other schizophrenia', category: 'Schizophrenia Spectrum' },
  { code: 'F20.9', description: 'Schizophrenia, unspecified', category: 'Schizophrenia Spectrum' },
  { code: 'F21', description: 'Schizotypal disorder', category: 'Schizophrenia Spectrum' },
  { code: 'F22', description: 'Delusional disorders', category: 'Schizophrenia Spectrum' },
  { code: 'F23', description: 'Brief psychotic disorder', category: 'Schizophrenia Spectrum' },
  { code: 'F24', description: 'Shared psychotic disorder', category: 'Schizophrenia Spectrum' },
  { code: 'F25.0', description: 'Schizoaffective disorder, bipolar type', category: 'Schizophrenia Spectrum' },
  { code: 'F25.1', description: 'Schizoaffective disorder, depressive type', category: 'Schizophrenia Spectrum' },
  { code: 'F25.8', description: 'Other schizoaffective disorders', category: 'Schizophrenia Spectrum' },
  { code: 'F25.9', description: 'Schizoaffective disorder, unspecified', category: 'Schizophrenia Spectrum' },
  { code: 'F28', description: 'Other psychotic disorder not due to a substance or known physiological condition', category: 'Schizophrenia Spectrum' },
  { code: 'F29', description: 'Unspecified psychosis not due to a substance or known physiological condition', category: 'Schizophrenia Spectrum' },

  // Personality Disorders (F60-F69)
  { code: 'F60.0', description: 'Paranoid personality disorder', category: 'Personality Disorders' },
  { code: 'F60.1', description: 'Schizoid personality disorder', category: 'Personality Disorders' },
  { code: 'F60.2', description: 'Antisocial personality disorder', category: 'Personality Disorders' },
  { code: 'F60.3', description: 'Borderline personality disorder', category: 'Personality Disorders' },
  { code: 'F60.4', description: 'Histrionic personality disorder', category: 'Personality Disorders' },
  { code: 'F60.5', description: 'Obsessive-compulsive personality disorder', category: 'Personality Disorders' },
  { code: 'F60.6', description: 'Avoidant personality disorder', category: 'Personality Disorders' },
  { code: 'F60.7', description: 'Dependent personality disorder', category: 'Personality Disorders' },
  { code: 'F60.81', description: 'Narcissistic personality disorder', category: 'Personality Disorders' },
  { code: 'F60.89', description: 'Other specific personality disorders', category: 'Personality Disorders' },
  { code: 'F60.9', description: 'Personality disorder, unspecified', category: 'Personality Disorders' },

  // Substance Use Disorders (F10-F19)
  { code: 'F10.10', description: 'Alcohol abuse, uncomplicated', category: 'Substance Use Disorders' },
  { code: 'F10.11', description: 'Alcohol abuse, in remission', category: 'Substance Use Disorders' },
  { code: 'F10.20', description: 'Alcohol dependence, uncomplicated', category: 'Substance Use Disorders' },
  { code: 'F10.21', description: 'Alcohol dependence, in remission', category: 'Substance Use Disorders' },
  { code: 'F11.10', description: 'Opioid abuse, uncomplicated', category: 'Substance Use Disorders' },
  { code: 'F11.11', description: 'Opioid abuse, in remission', category: 'Substance Use Disorders' },
  { code: 'F11.20', description: 'Opioid dependence, uncomplicated', category: 'Substance Use Disorders' },
  { code: 'F11.21', description: 'Opioid dependence, in remission', category: 'Substance Use Disorders' },
  { code: 'F12.10', description: 'Cannabis abuse, uncomplicated', category: 'Substance Use Disorders' },
  { code: 'F12.11', description: 'Cannabis abuse, in remission', category: 'Substance Use Disorders' },
  { code: 'F12.20', description: 'Cannabis dependence, uncomplicated', category: 'Substance Use Disorders' },
  { code: 'F12.21', description: 'Cannabis dependence, in remission', category: 'Substance Use Disorders' },
  { code: 'F13.10', description: 'Sedative, hypnotic or anxiolytic abuse, uncomplicated', category: 'Substance Use Disorders' },
  { code: 'F13.11', description: 'Sedative, hypnotic or anxiolytic abuse, in remission', category: 'Substance Use Disorders' },
  { code: 'F13.20', description: 'Sedative, hypnotic or anxiolytic dependence, uncomplicated', category: 'Substance Use Disorders' },
  { code: 'F13.21', description: 'Sedative, hypnotic or anxiolytic dependence, in remission', category: 'Substance Use Disorders' },
  { code: 'F14.10', description: 'Cocaine abuse, uncomplicated', category: 'Substance Use Disorders' },
  { code: 'F14.11', description: 'Cocaine abuse, in remission', category: 'Substance Use Disorders' },
  { code: 'F14.20', description: 'Cocaine dependence, uncomplicated', category: 'Substance Use Disorders' },
  { code: 'F14.21', description: 'Cocaine dependence, in remission', category: 'Substance Use Disorders' },
  { code: 'F15.10', description: 'Other stimulant abuse, uncomplicated', category: 'Substance Use Disorders' },
  { code: 'F15.11', description: 'Other stimulant abuse, in remission', category: 'Substance Use Disorders' },
  { code: 'F15.20', description: 'Other stimulant dependence, uncomplicated', category: 'Substance Use Disorders' },
  { code: 'F15.21', description: 'Other stimulant dependence, in remission', category: 'Substance Use Disorders' },

  // ADHD and Neurodevelopmental (F90-F98)
  { code: 'F90.0', description: 'Attention-deficit hyperactivity disorder, predominantly inattentive type', category: 'Neurodevelopmental Disorders' },
  { code: 'F90.1', description: 'Attention-deficit hyperactivity disorder, predominantly hyperactive type', category: 'Neurodevelopmental Disorders' },
  { code: 'F90.2', description: 'Attention-deficit hyperactivity disorder, combined type', category: 'Neurodevelopmental Disorders' },
  { code: 'F90.8', description: 'Attention-deficit hyperactivity disorder, other type', category: 'Neurodevelopmental Disorders' },
  { code: 'F90.9', description: 'Attention-deficit hyperactivity disorder, unspecified type', category: 'Neurodevelopmental Disorders' },
  { code: 'F91.0', description: 'Conduct disorder confined to family context', category: 'Neurodevelopmental Disorders' },
  { code: 'F91.1', description: 'Conduct disorder, childhood-onset type', category: 'Neurodevelopmental Disorders' },
  { code: 'F91.2', description: 'Conduct disorder, adolescent-onset type', category: 'Neurodevelopmental Disorders' },
  { code: 'F91.3', description: 'Oppositional defiant disorder', category: 'Neurodevelopmental Disorders' },
  { code: 'F91.8', description: 'Other conduct disorders', category: 'Neurodevelopmental Disorders' },
  { code: 'F91.9', description: 'Conduct disorder, unspecified', category: 'Neurodevelopmental Disorders' },
  { code: 'F93.0', description: 'Separation anxiety disorder of childhood', category: 'Neurodevelopmental Disorders' },
  { code: 'F94.0', description: 'Selective mutism', category: 'Neurodevelopmental Disorders' },
  { code: 'F94.1', description: 'Reactive attachment disorder of childhood', category: 'Neurodevelopmental Disorders' },
  { code: 'F94.2', description: 'Disinhibited attachment disorder of childhood', category: 'Neurodevelopmental Disorders' },
  { code: 'F98.0', description: 'Enuresis not due to a substance or known physiological condition', category: 'Neurodevelopmental Disorders' },
  { code: 'F98.1', description: 'Encopresis not due to a substance or known physiological condition', category: 'Neurodevelopmental Disorders' },

  // Autism Spectrum (F84)
  { code: 'F84.0', description: 'Autistic disorder', category: 'Autism Spectrum' },
  { code: 'F84.2', description: "Rett's syndrome", category: 'Autism Spectrum' },
  { code: 'F84.3', description: 'Other childhood disintegrative disorder', category: 'Autism Spectrum' },
  { code: 'F84.5', description: "Asperger's syndrome", category: 'Autism Spectrum' },
  { code: 'F84.8', description: 'Other pervasive developmental disorders', category: 'Autism Spectrum' },
  { code: 'F84.9', description: 'Pervasive developmental disorder, unspecified', category: 'Autism Spectrum' },

  // Eating Disorders (F50)
  { code: 'F50.00', description: 'Anorexia nervosa, unspecified', category: 'Eating Disorders' },
  { code: 'F50.01', description: 'Anorexia nervosa, restricting type', category: 'Eating Disorders' },
  { code: 'F50.02', description: 'Anorexia nervosa, binge eating/purging type', category: 'Eating Disorders' },
  { code: 'F50.2', description: 'Bulimia nervosa', category: 'Eating Disorders' },
  { code: 'F50.81', description: 'Binge eating disorder', category: 'Eating Disorders' },
  { code: 'F50.82', description: 'Avoidant/restrictive food intake disorder', category: 'Eating Disorders' },
  { code: 'F50.89', description: 'Other specified eating disorder', category: 'Eating Disorders' },
  { code: 'F50.9', description: 'Eating disorder, unspecified', category: 'Eating Disorders' },

  // Sleep Disorders (F51, G47)
  { code: 'F51.01', description: 'Primary insomnia', category: 'Sleep Disorders' },
  { code: 'F51.02', description: 'Adjustment insomnia', category: 'Sleep Disorders' },
  { code: 'F51.03', description: 'Paradoxical insomnia', category: 'Sleep Disorders' },
  { code: 'F51.04', description: 'Psychophysiologic insomnia', category: 'Sleep Disorders' },
  { code: 'F51.05', description: 'Insomnia due to other mental disorder', category: 'Sleep Disorders' },
  { code: 'F51.09', description: 'Other insomnia not due to a substance or known physiological condition', category: 'Sleep Disorders' },
  { code: 'F51.11', description: 'Primary hypersomnia', category: 'Sleep Disorders' },
  { code: 'F51.12', description: 'Insufficient sleep syndrome', category: 'Sleep Disorders' },
  { code: 'F51.13', description: 'Hypersomnia due to other mental disorder', category: 'Sleep Disorders' },
  { code: 'G47.00', description: 'Insomnia, unspecified', category: 'Sleep Disorders' },
  { code: 'G47.10', description: 'Hypersomnia, unspecified', category: 'Sleep Disorders' },
  { code: 'G47.20', description: 'Circadian rhythm sleep disorder, unspecified type', category: 'Sleep Disorders' },
  { code: 'G47.30', description: 'Sleep apnea, unspecified', category: 'Sleep Disorders' },

  // Intellectual Disabilities (F70-F79)
  { code: 'F70', description: 'Mild intellectual disabilities', category: 'Intellectual Disabilities' },
  { code: 'F71', description: 'Moderate intellectual disabilities', category: 'Intellectual Disabilities' },
  { code: 'F72', description: 'Severe intellectual disabilities', category: 'Intellectual Disabilities' },
  { code: 'F73', description: 'Profound intellectual disabilities', category: 'Intellectual Disabilities' },
  { code: 'F78', description: 'Other intellectual disabilities', category: 'Intellectual Disabilities' },
  { code: 'F79', description: 'Unspecified intellectual disabilities', category: 'Intellectual Disabilities' },

  // Other Common Codes
  { code: 'F43.8', description: 'Other reactions to severe stress', category: 'Trauma and Stress' },
  { code: 'F43.9', description: 'Reaction to severe stress, unspecified', category: 'Trauma and Stress' },
  { code: 'F48.1', description: 'Depersonalization-derealization syndrome', category: 'Dissociative Disorders' },
  { code: 'F44.0', description: 'Dissociative amnesia', category: 'Dissociative Disorders' },
  { code: 'F44.1', description: 'Dissociative fugue', category: 'Dissociative Disorders' },
  { code: 'F44.81', description: 'Dissociative identity disorder', category: 'Dissociative Disorders' },
  { code: 'F44.9', description: 'Dissociative disorder, unspecified', category: 'Dissociative Disorders' },
  { code: 'F52.0', description: 'Hypoactive sexual desire disorder', category: 'Sexual Disorders' },
  { code: 'F52.21', description: 'Male erectile disorder', category: 'Sexual Disorders' },
  { code: 'F52.22', description: 'Female sexual arousal disorder', category: 'Sexual Disorders' },
  { code: 'F52.31', description: 'Female orgasmic disorder', category: 'Sexual Disorders' },
  { code: 'F52.32', description: 'Male orgasmic disorder', category: 'Sexual Disorders' },
  { code: 'F52.4', description: 'Premature ejaculation', category: 'Sexual Disorders' },
  { code: 'F52.6', description: 'Dyspareunia not due to a substance or known physiological condition', category: 'Sexual Disorders' },
  { code: 'F64.0', description: 'Transsexualism', category: 'Gender Dysphoria' },
  { code: 'F64.1', description: 'Dual role transvestism', category: 'Gender Dysphoria' },
  { code: 'F64.2', description: 'Gender identity disorder of childhood', category: 'Gender Dysphoria' },
  { code: 'F64.8', description: 'Other gender identity disorders', category: 'Gender Dysphoria' },
  { code: 'F64.9', description: 'Gender identity disorder, unspecified', category: 'Gender Dysphoria' },
  { code: 'Z63.0', description: 'Problems in relationship with spouse or partner', category: 'Other Conditions' },
  { code: 'Z63.4', description: 'Disappearance and death of family member', category: 'Other Conditions' },
  { code: 'Z63.5', description: 'Disruption of family by separation and divorce', category: 'Other Conditions' },
  { code: 'Z65.0', description: 'Conviction in civil and criminal proceedings without imprisonment', category: 'Other Conditions' },
  { code: 'Z65.1', description: 'Imprisonment and other incarceration', category: 'Other Conditions' },
  { code: 'Z65.2', description: 'Problems related to release from prison', category: 'Other Conditions' },
  { code: 'Z65.3', description: 'Problems related to other legal circumstances', category: 'Other Conditions' },
  { code: 'Z65.4', description: 'Victim of crime and terrorism', category: 'Other Conditions' },
  { code: 'Z65.5', description: 'Exposure to disaster, war and other hostilities', category: 'Other Conditions' },
];

export const searchICD10Codes = (query: string): ICD10Code[] => {
  if (!query || query.trim() === '') return icd10MentalHealthCodes;
  
  const searchTerm = query.toLowerCase().trim();
  
  return icd10MentalHealthCodes.filter(code => 
    code.code.toLowerCase().includes(searchTerm) ||
    code.description.toLowerCase().includes(searchTerm) ||
    code.category.toLowerCase().includes(searchTerm)
  );
};
