project_id = "fpzuxwynuivqdyltpydj"

[functions.health-check]
verify_jwt = false

[functions.cleanup-rate-limits]
verify_jwt = false

[functions.transcribe-session]
verify_jwt = true

[functions.generate-clinical-note]
verify_jwt = true

[functions.generate-intake-note]
verify_jwt = true

[functions.suggest-clinical-content]
verify_jwt = true

[functions.check-openai-key]
verify_jwt = true

[functions.confirm-appointment]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.notify-waitlist-slots]
verify_jwt = true

[functions.send-appointment-notification]
verify_jwt = true

[functions.send-appointment-reminder]
verify_jwt = true

[functions.send-waitlist-email]
verify_jwt = true

[functions.generate-section-content]
verify_jwt = true

[functions.sunday-lockout]
verify_jwt = false

[functions.check-compliance]
verify_jwt = false

[functions.generate-treatment-plan]
verify_jwt = true

[functions.supervision-notifications]
verify_jwt = false

[functions.cosignature-status-monitor]
verify_jwt = false

[functions.cosignature-workflow]
verify_jwt = true

[functions.transcribe-and-generate-note]
verify_jwt = true

[functions.telehealth-consent-renewal]
verify_jwt = false

[functions.waiting-room-timeout]
verify_jwt = false

[functions.send-waiting-room-notification]
verify_jwt = false

[functions.verify-incident-to-compliance]
verify_jwt = true

[functions.create-portal-user]
verify_jwt = true

[functions.send-portal-invitation]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.create-test-portal-user]
verify_jwt = true

[functions.scan-uploaded-file]
verify_jwt = true

[functions.send-staff-invitation]
verify_jwt = true

[functions.send-admin-password-reset]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.log-auth-attempt]
verify_jwt = false

[functions.send-portal-form-notification]
verify_jwt = true

[functions.send-portal-form-bulk-notification]
verify_jwt = true


